on:
  push:
    branches:
      - main
    paths:
      - redirects.json
  workflow_dispatch: # For manual retry

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - name: Build
        run: |
          ./bin/build
      - name: Check if docs files are updated
        id: git-diff
        run: |
          git add --intent-to-add ./docs
          git diff --exit-code
        continue-on-error: true
      - name: Commit changes and push
        if: steps.git-diff.outcome == 'failure'
        run: |
          # https://api.github.com/users/github-actions%5Bbot%5D
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add ./docs
          git commit -m '[Bot] Build docs'
          git push
